[package]
name = "day19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/main.rs"

[dependencies]
anyhow = "1.0.68"
nom = "7.1.1"
num-integer = "0.1.45"
rayon = "1.6.1"
regex = "1.7.0"
