[package]
name = "day14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/main.rs"

[dependencies]
anyhow = "1.0.68"
itertools = "0.10.5"
nom = "7.1.1"
